---

- name: Install apt repos
  sudo: yes
  apt_repository: repo={{ item }} validate_certs=no
  with_items: apt_repos

- name: Update apt
  apt: update_cache=yes
  sudo: yes

- name: Install packages
  action: apt pkg={{ item }} state=latest
  sudo: yes
  with_items: apt_packages

- include: silex.yml

- name: Create xvfb startup script
  template: src=xvfb.j2 dest=/etc/init.d/xvfb  mode=0750

- name: Enable xvfb on boot
  sudo: yes
  shell: update-rc.d xvfb defaults 10

- name: Enable xvfb
  sudo: yes
  shell: service xvfb restart
