---

- name: Clone/Update repo
  git: repo=https://github.com/M1r1k/wkhtmltopdf_php_saas.git dest=/var/wkhtmltopdf version=master force=yes

- name: Run composer updates
  shell: cd /var/wkhtmltopdf && composer up
