---

- name: Clone/Update repo
  git: repo=https://github.com/M1r1k/wkhtmltopdf_php_saas.git dest=/var/wkhtmltopdf version=master force=yes

- name: Run composer updates
  shell: cd /var/wkhtmltopdf && composer up

- name: Give permissions to webserver
  file: path=/var/wkhtmltopdf recurse=yes state=directory mode="u=rwx,g=r,o=r" owner=www-data group=www-data
