---

- name: Clone/Update repo
  git: repo=https://github.com/M1r1k/wkhtmltopdf_php_saas.git dest=/var/www/wkhtmltopdf refspec=+refs/pull/*:refs/heads/*

- name: Run composer updates
  shell: cd /var/www/wkhtmltopdf && composer up