---
vagrantfile-local:
    vm:
        box: ubuntu/trusty64
        network:
            private_network: 192.168.1.2
            forwarded_port:
                CocLsFE7aIwA:
                    host: '8081'
                    guest: '80'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                    memory: '1024'
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
            lxc:
                box: fgrehm/precise64-lxc
                box_url: https://atlas.hashicorp.com/fgrehm/boxes/precise64-lxc/versions/1.2.0/providers/lxc.box
        synced_folder:
            8Q9vTs08YuK2:
                source: ./
                target: /var/www
                nfs: 'true'
        usable_port_range: 2200..2250
    vagrant:
        host: detect
