---

- hosts: all

  roles:
    - { role: cibox-swap }
    - { role: wkhtmltopdf-service }
    - { role: ansible-role-ansible }
    - { role: ansible-role-apache }
    - { role: ansible-role-php }
    - { role: ansible-role-php-xhprof }
