---

apt_repos:
  - ppa:ansible/ansible

apt_packages:
  - htop
  - vim
  - time
  - tree
  - make
  - ansible
  - git
  - xfonts-100dpi
  - xfonts-75dpi
  - xfonts-scalable
  - xfonts-cyrillic
  - xvfb
  - x11-apps
  - imagemagick
  - openssl
  - build-essential
  - xorg
  - libssl-dev

wkhtmltopdf_package_name: wkhtmltopdf
wkhtmltopdf_package_url: http://downloads.sourceforge.net/wkhtmltopdf/wkhtmltox-0.12.2.1_linux-trusty-amd64.deb
